#!/bin/bash
# Complete Deployment Guide - NYC Crashes Dashboard
# Backend: Render | Frontend: Netlify

echo "🚀 NYC Crashes Dashboard - Full Stack Deployment"
echo "=================================================="
echo ""
echo "This guide will help you deploy:"
echo "  📦 Backend (Flask API) → Render"
echo "  🎨 Frontend (React) → Netlify"
echo ""

# STEP 1: GitHub Setup
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 1: GitHub Setup"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Create a new repository on GitHub"
echo "   → Go to https://github.com/new"
echo "   → Name: nyc-crashes-dashboard"
echo "   → Make it PUBLIC"
echo "   → Click 'Create repository'"
echo ""
echo "2. Push code to GitHub:"
echo "   git init"
echo "   git add ."
echo "   git commit -m 'Initial commit - NYC crashes dashboard'"
echo "   git remote add origin https://github.com/YOUR_USERNAME/nyc-crashes-dashboard.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
read -p "✅ Press Enter when you've pushed to GitHub..."

# STEP 2: Deploy Backend
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 2: Deploy Backend on Render"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to https://render.com"
echo "2. Sign up with GitHub"
echo "3. Click 'New +' → 'Web Service'"
echo "4. Connect your GitHub repository"
echo "5. Configure with these settings:"
echo ""
echo "   📋 Configuration:"
echo "   • Name: nyc-crashes-backend"
echo "   • Environment: Python 3"
echo "   • Build Command: cd backend && pip install -r requirements.txt"
echo "   • Start Command: cd backend && gunicorn app:app"
echo "   • Plan: Free"
echo ""
echo "6. Click 'Create Web Service'"
echo "7. Wait for deployment to complete (~2-3 minutes)"
echo ""
echo "8. Once deployed, copy your backend URL from the dashboard"
echo "   Format: https://nyc-crashes-backend.onrender.com"
echo ""
read -p "✅ Enter your Render backend URL: " BACKEND_URL
if [ -z "$BACKEND_URL" ]; then
  echo "❌ Backend URL is required!"
  exit 1
fi

# STEP 3: Update Frontend Config
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 3: Update Frontend Configuration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Updating frontend/netlify.toml with your backend URL..."
echo ""

# Update netlify.toml
sed -i "s|VITE_BACKEND_URL = .*|VITE_BACKEND_URL = \"$BACKEND_URL\"|" frontend/netlify.toml

echo "✅ Updated frontend/netlify.toml"
echo ""
echo "Now commit and push this change:"
echo "   git add frontend/netlify.toml"
echo "   git commit -m 'Update backend URL for production'"
echo "   git push"
echo ""
read -p "✅ Press Enter when you've pushed the updated config..."

# STEP 4: Deploy Frontend
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 4: Deploy Frontend on Netlify"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to https://netlify.com"
echo "2. Sign up with GitHub"
echo "3. Click 'Add new site' → 'Import an existing project'"
echo "4. Click 'GitHub' and authorize"
echo "5. Select your repository"
echo "6. Configure with these settings:"
echo ""
echo "   📋 Configuration:"
echo "   • Build Command: cd frontend && npm install && npm run build"
echo "   • Publish Directory: frontend/dist"
echo ""
echo "7. Click 'Deploy site'"
echo "8. Wait for deployment (~3-5 minutes)"
echo ""
echo "9. Once deployed, you'll get a URL like:"
echo "   https://your-site-name.netlify.app"
echo ""
read -p "✅ Enter your Netlify frontend URL: " FRONTEND_URL
if [ -z "$FRONTEND_URL" ]; then
  echo "❌ Frontend URL is required!"
  exit 1
fi

# STEP 5: Verify Deployment
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "STEP 5: Verify Deployment"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Testing backend API..."
echo ""
echo "Open in your browser or use curl:"
echo "  curl $BACKEND_URL/api/health"
echo ""
echo "If you see {'status': 'ok', ...} then backend is working! ✅"
echo ""

# FINAL SUMMARY
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✨ DEPLOYMENT COMPLETE!"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Your dashboard is now live!"
echo ""
echo "📊 Frontend: $FRONTEND_URL"
echo "🔧 Backend: $BACKEND_URL"
echo ""
echo "📱 Share this URL with anyone to use your dashboard:"
echo "   $FRONTEND_URL"
echo ""
echo "💡 Tips:"
echo "   • Render free tier sleeps after 15 min of inactivity"
echo "   • First request after sleep takes ~30 seconds"
echo "   • For production, upgrade to paid plans"
echo "   • Monitor logs in Render & Netlify dashboards"
echo ""
echo "🔗 Links:"
echo "   • Render Dashboard: https://dashboard.render.com"
echo "   • Netlify Dashboard: https://app.netlify.com"
echo "   • GitHub: https://github.com/YOUR_USERNAME/nyc-crashes-dashboard"
echo ""
echo "✅ You're all set! Enjoy your dashboard!"
